### ISSUE TITLE
solarisvm and virtual box

### ISSUE THREAD

**Issue by tvatter** [jeroen/solarisvm#3]
Hi,

A colleague and I tried to open the image in both virtual box and VMWare player on both OSX Sierra and Linux Mint, and nothing is happening.

Essentially, it gets to the screen where you need to choose between standard and safe mode, you enter standard, and it brings you back to the same screen... and safe mode doesn't work either.

Any advice on how to use it?

Thanks a lot,
Thibault

**Comment by jeroen** [comment]
I use vmware fusion on OSX and it works fine.

**Comment by tvatter** [comment]
Thanks, trying that right now!

**Comment by tvatter** [comment]
Same issue with vmware fusion, that's super weird.

**Comment by tvatter** [comment]
My bad, I tried with solaris 64bit initially, I tried again with Solaris 10 only, and it works, thanks a lot!
