### ISSUE TITLE
Instructions for R-devel (GNU toolchain flavor)

### ISSUE THREAD

**Issue by jcheng5** [jeroen/solarisvm#5]
Hi @jeroen, this VM is an absolute godsend, thank you! It's saved me many hours in tracking down Solaris-only issues reported by CRAN.

I recently needed to reproduce a failed `R CMD check` on a more recent version of R than the 3.3.0 that is available from opencsw, and it took quite a bit of time for me to figure out how to get R-devel building from source.

I've documented the steps involved in [this gist](https://gist.github.com/jcheng5/ca6c6b693b743a01d458a2872b039ab6)--I hope you or other users of this repo find it helpful.

**Comment by jeroen** [comment]
Thanks, I'll add the link to the readme.
